### ISSUE TITLE
Diode Drive Binary Not Running On Linux

### ISSUE THREAD

**Issue by zach-pagel** [diodechain/diode_drive_feedback#124]
**OS:** Ubuntu Linux
**Diode Drive Version:** Whatever binary was hosted at [diode.io/download](https://diode.io/download) on January 10th.

Diode Drive quit connecting to the network and the UI was glitching. I probably switched from a pre-multisig dev branch (from source) to multisig nightly (from binary), so I cleared ~/.config/ddrive, deleted ~/dDrive, and then reinstalled Diode Drive from the website binary. Now I get this in the debug log when starting Diode Drive. Same behavior for Stable and Nightly.

`03:36:42.816 [error] Process #PID<0.1917.0> on node :"ddrive_5104@127.0.0.1" raised an exception
 (BadFunctionError) function #Function<4.105815022/0 in Ddrive> is invalid, likely because it points to an old version of the code
    :erlang.apply/2
03:36:42.816 [error] Process #PID<51242.1917.0> on node :"ddrive_5104@127.0.0.1" raised an exception
 (BadFunctionError) function #Function<4.105815022/0 in Ddrive.focus/1> is invalid, likely because it points to an old version of the code
    :erlang.apply/2`

**Comment by zach-pagel** [comment]
That worked great! Stable binary launches fine now, although there is seemingly still no network connectivity (no green online indications, no file sync or chain transactions going through). Also the invite code/link setting has disappeared from the zone settings page. Nothing in the error log.

**Comment by jimthedj65** [comment]
I can confirm that there is no activity from my side. I had a MAC OSX crash and after a reboot, it started with the network sync activity.

**Comment by jimthedj65** [comment]
it is relevant or similar to this issue https://github.com/diodechain/diode_drive_feedback/issues/78

**Comment by jimthedj65** [comment]
my logs revealed 
`09:52:13.311 [error] Process #PID<0.3033.0> on node :"ddrive@Jamess-MacBook-Pro" raised an exception
** (MatchError) no match of right hand side value: nil
    (ddrive 1.2.1) lib/folder.ex:50: Folder.connection/2
    (ddrive 1.2.1) lib/remote_drive.ex:91: RemoteDrive.send_message/3
    (ddrive 1.2.1) lib/model/message.ex:228: Model.Message.send_message/2
09:53:57.651 [info] <0.3140.0> DiodeClient waiting for connection
09:54:02.746 [info] <0.3145.0> DiodeClient waiting for connection`

**Comment by jimthedj65** [comment]
`09:54:06.548 [info] <0.2967.0> DiodeClient.Port Port.terminate({noproc,
                                            [{erlang,link,
                                              [<0.2899.0>],
                                              [{error_info,
                                                #{module =>
                                                   erl_erts_errors}}]},
                                             {'Elixir.DiodeClient.Connection',
                                              call,2,
                                              [{file,
                                                "lib/diode_client/connection.ex"},
                                               {line,710}]},
                                             {'Elixir.DiodeClient.Port',
                                              handle_call,3,
                                              [{file,
                                                "lib/diode_client/port.ex"},
                                               {line,118}]},
                                             {gen_server,try_handle_call,4,
                                              [{file,"gen_server.erl"},
                                               {line,725}]},`

**Comment by zach-pagel** [comment]
@hansr sent me a message via diode drive and everything revived. It works totally fine now.
