### ISSUE TITLE
"out of file descriptors" error on Mac

### ISSUE THREAD

**Issue by hansr** [diodechain/diode_drive_feedback#129]
**System:** MacOS Catalina, Diode Drive 1.4.1 (and probably earlier as well)

**Description:** I added my 35th zone and Diode Drive stopped opening.  It acted strangely and would only partially work.  However, if I switched profiles to another profile with less zones, it worked fine.  To fix, I unlinked five zones and everything kicked back into gear.  It is not out of the question that this could have been exacerbated by a broken DB on one of the zones I was able to unlink.  The other circumstances surrounding were: a) I could run from source on same profile and it worked fine b) the issue seemed to crop up when an update was being applied and failed (updater crashed) c) disabling system access from updater seemed to change the behavior (but didn't fix it) (e.g. /etc/hosts disable updater URL)

Debug log showed "out of file descriptions" on Mac:
```
12:30:24.894 [error] Process #PID<0.6413.0> terminating
** (ErlangError) Erlang error: :emfile
    :erlang.open_port({:spawn_executable, '/Applications/dDrive.app/Contents/Resources/lib/fs-6.12.0/priv/mac_listener'}, [:stream, :exit_status, :binary, {:line, 16384}, {:args, ['-F', "/Users/hr/DistributedDrives/**REDACT**"]}, {:cd, "/Users/hr/DistributedDrives/**REDACT**"}])
    (fs 6.12.0) /Users/administrator/projects/ddrive/deps/fs/src/fs_server.erl:11: :fs_server.init/1
    (stdlib 3.15) gen_server.erl:427: :gen_server.init_it/2
    (stdlib 3.15) gen_server.erl:394: :gen_server.init_it/6
    (stdlib 3.15) proc_lib.erl:226: :proc_lib.init_p_do_apply/3

Start Call: FibSupervisor.start_worker(FileMonitor, FileMonitor, ["/Users/hr/DistributedDrives/**REDACT**"], true)
Restart: :permanent
Shutdown: 5000
Type: :worker
12:30:54.850 [info] <0.2024.0> FibSupervisor Started /Users/hr/DistributedDrives/**REDACT** after 108ms
12:30:54.851 [info] <0.2096.0> DriveMonitor Starting Zone '**REDACT**': {:error, {{:shutdown, {:failed_to_start_child, FileMonitor, {:shutdown, {:failed_to_start_child, :fs_server, {:emfile, [{:erlang, :open_port, [{:spawn_executable, '/Applications/dDrive.app/Contents/Resources/lib/fs-6.12.0/priv/mac_listener'}, [:stream, :exit_status, :binary, {:line, 16384}, {:args, ['-F', "/Users/hr/DistributedDrives/**REDACT**"]}, {:cd, "/Users/hr/DistributedDrives/**REDACT**"}]], [error_info: %{module: :erl_erts_errors}]}, {:fs_server, :init, 1, [file: '/Users/administrator/projects/ddrive/deps/fs/src/fs_server.erl', line: 11]}, {:gen_server, :init_it, 2, [file: 'gen_server.erl', line: 427]}, {:gen_server, :init_it, 6, [file: 'gen_server.erl', line: 394]}, {:proc_lib, :init_p_do_apply, 3, [file: 'proc_lib.erl', line: 226]}]}}}}}, {:child, :undefined, :"/Users/hr/DistributedDrives/**REDACT**", {FibSupervisor, :start_worker, [Folder, :"/Users/hr/DistributedDrives/**REDACT**", ["/Users/hr/DistributedDrives/**REDACT**", nil], true]}, :permanent, 5000, :worker, [FibSupervisor]}}}
12:30:57.456 [info] Showing http://localhost:58823/drive/Diode-internal?k=IPFJLHLVWB6WNPDLEXNWB5YXWVLX666JRYDTIXBTMAQ34EJSGJBQ
12:30:57.530 [debug] Processing with Phoenix.LiveView.Plug.Elixir.DdriveWeb.DriveHomeLive/2
  Parameters: %{"drive" => "Diode-internal", "k" => "IPFJLHLVWB6WNPDLEXNWB5YXWVLX666JRYDTIXBTMAQ34EJSGJBQ"}
  Pipelines: [:browser]
12:30:57.640 [warn] Ranch acceptor reducing accept rate: out of file descriptors

12:30:57.641 [warn] Ranch acceptor reducing accept rate: out of file descriptors

12:30:57.647 [warn] Ranch acceptor reducing accept rate: out of file descriptors

12:30:57.650 [warn] Ranch acceptor reducing accept rate: out of file descriptors

12:30:57.692 [info] Showing http://localhost:58823/drive/Diode-internal?k=IPFJLHLVWB6WNPDLEXNWB5YXWVLX666JRYDTIXBTMAQ34EJSGJBQ
12:30:57.694 [error] Process #PID<0.6864.0> on node :"ddrive_23039@127.0.0.1" raised an exception
** (ErlangError) Erlang error: :emfile
    :erlang.open_port({:spawn_executable, '/usr/bin/open'}, [:stderr_to_stdout, :use_stdio, :exit_status, :binary, :hide, {:args, ["-a", "dDrive"]}])
    (elixir 1.11.4) lib/system.ex:830: System.cmd/3
12:30:57.694 [error] Child DriveWindow of Supervisor Ddrive terminated
** (exit) an exception was raised:
    ** (ErlangError) Erlang error: :emfile
        :erlang.open_port({:spawn_executable, '/usr/bin/open'}, [:stderr_to_stdout, :use_stdio, :exit_status, :binary, :hide, {:args, ["-a", "dDrive"]}])
        (elixir 1.11.4) lib/system.ex:830: System.cmd/3
Pid: #PID<0.2438.0>
Start Call: FibSupervisor.start_worker(Desktop.Window, DriveWindow, [[app: :ddrive, id: DriveWindow, title: "Diode Drive", size: {900, 650}, icon: "diode.png", menubar: UI.MenuBar, icon_menu: UI.Menu, url: &DdriveWeb.default_url/0, hidden: true]], true)
Restart: :permanent
Shutdown: 5000
Type: :worker
12:30:57.695 [info] <0.2024.0> FibSupervisor Starting Elixir.DriveWindow
```

**Comment by dominicletz** [comment]
Quite curious, we're adding probably just 1 file descriptor per new zone and the default limit on macos seems to be 1000. Will have to check what the actual file descriptor allocation is.

**Comment by hansr** [comment]
Fixed
